"use client";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { darkerGrotesque } from "@/public/fonts";
import Image from "next/image";

type Props = {};

export default function ImageSlider({}: Props) {
  const settings = {
    dots: true,
    infinite: true,
    speed: 1000,
    slidesToShow: 3,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 1000,
  };

  return (
    <section className="py-14">
      <div className=" flex flex-col">
        <div className="container">
          {" "}
          <h3
            className={`${darkerGrotesque.className} font-semibold text-[35px] md:text-[46px]`}
          >
            Journey Through Art of community
          </h3>
        </div>

        <Slider {...settings} className="flex mt-8 gap-12 w-full h-[500px]">
          <figure className="w-[95%] mx-auto outline-none">
            <Image
              src="/assets/images/image-slider1.png"
              alt="Image slider 1 "
              width={600}
              height={500}
              className="w-[95%] mx-auto"
            />
          </figure>
          <div className="grid grid-cols-1 gap-5 w-[95%] mx-auto outline-none">
            <Image
              src="/assets/images/image-slider2.png"
              alt="Image slider 1 "
              width={200}
              height={300}
              className="h-[200px] w-[95%] mx-auto"
            />
            <div className="w-[95%] flex items-center mt-3 py-5 flex-col bg-[#19161C] mx-auto">
              <h4 className="text-[#D2FF3A] font-medium text-[32px] md:text-[40px]">
                48,000
              </h4>
              <p className=" uppercase ">
                Images generated by artificial intelligence
              </p>
            </div>
          </div>
          <figure className="w-[95%] mx-auto outline-none">
            <Image
              src="/assets/images/image-slider1.png"
              alt="Image slider 1 "
              width={600}
              height={500}
              className="w-[95%] mx-auto"
            />
          </figure>
          <figure className="w-[95%] mx-auto outline-none">
            <Image
              src="/assets/images/image-slider1.png"
              alt="Image slider 1 "
              width={600}
              height={500}
              className="w-[95%] mx-auto"
            />
          </figure>
          <figure className="w-[95%] mx-auto outline-none">
            <Image
              src="/assets/images/image-slider1.png"
              alt="Image slider 1 "
              width={600}
              height={500}
              className="w-[95%] mx-auto"
            />
          </figure>
        </Slider>
      </div>
    </section>
  );
}
